### ISSUE TITLE
nested workflow

### ISSUE THREAD

**Issue by Amirsharifico** [designitycom/web-services#54]
I am trying to create a nested workflow but these are the blockers:

- How to have 2 sets of activities in a single workflow
or
- how to invoke a workflow within another workflow?
`  TypeError: Failed to initialize workflow of type 'createMintWF': no such function is exported by the workflow bundle
      at Object.initRuntime (/home/amirsharifico/web-services/node_modules/@temporalio/workflow/src/worker-interface.ts:151:10)
      at evalmachine.<anonymous>:1:18
      at Script.runInContext (node:vm:141:12)
      at Object.runInContext (node:vm:291:6)
      at Proxy.<anonymous> (/home/amirsharifico/web-services/node_modules/@temporalio/worker/lib/workflow/vm.js:36:46)
      at VMWorkflowCreator.createWorkflow (/home/amirsharifico/web-services/node_modules/@temporalio/worker/lib/workflow/vm.js:43:24)
      at async handleRequest (/home/amirsharifico/web-services/node_modules/@temporalio/worker/lib/workflow/workflow-worker-thread.js:42:13)
      at async MessagePort.<anonymous> (/home/amirsharifico/web-services/node_modules/@temporalio/worker/lib/workflow/workflow-worker-thread.js:83:32),
  workflowExists: false
}`

**Comment by Amirsharifico** [comment]
@saber @mehdidehdar 
may I have your help to know how to export a workflow? I am facing below error :
`{
  "message": "Failed to initialize workflow of type 'createMintWF': no such function is exported by the workflow bundle",
  "source": "TypeScriptSDK",
  "stackTrace": "/home/amirsharifico/web-services/workflow-bundle-655f6353bb0db4fa52c0.js:3407\n        throw new TypeError(`Failed to initialize workflow of type '${info.workflowType}': ${details}`);\n        ^\n\nTypeError: Failed to initialize workflow of type 'createMintWF': no such function is exported by the workflow bundle\n    at Object.initRuntime (/home/amirsharifico/web-services/node_modules/@temporalio/workflow/src/worker-interface.ts:151:10)\n    at evalmachine.<anonymous>:1:18",
  "encodedAttributes": null,
  "cause": null
}`

**Comment by saberistic** [comment]
Is this still a problem?

**Comment by Amirsharifico** [comment]
Nope, I close the issue
